#!/bin/sh

. /lib/functions.sh
. /lib/functions/network.sh
. /usr/share/libubox/jshn.sh

[ -x /sbin/swconfig -a -r /etc/board.json ] || exit 1

INTERVAL=2	# Sleep interval in Seconds
PREVSTATE=-1	# -1 = Don't Know, 0 = Down, 1 = Up
WAN=wan
DEV=eth0.2
PHY=eth0
SWITCH=switch0
WANPORT=4

watch() {
	logger "monitor connections on wan(eth0.2)"

	while $(/bin/ubus call network.interface.wan status &> /dev/null); do
		link=$(swconfig dev switch0 port 4 get link)
		case "$link" in
		*"link:up"*)
			[ "$PREVSTATE" = "1" ] || {
				logger "Detected Interface UP"
				[ "$PREVSTATE" = "0" ] && {
					ip link set eth0.2 up
					ubus call network.interface.wan renew
				}
			}
			PREVSTATE=1
			;;
		*"link:down"*)
			[ "$PREVSTATE" = "0" ] || {
				logger "Detected Interface DOWN"
				[ "$PREVSTATE" = "1" ] && {
					ip link set eth0.2 down
				}
			}
			PREVSTATE=0
			;;
		esac
		sleep $INTERVAL
	done
}

logger "Started wan-sms"
while (/bin/true); do

	watch

	echo wait
	sleep 10
done

